full_tutorial/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @UniqueEntity(fields={"email", "name"}, message="It looks like your already have an account!")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
//    const ROLE_USER = 'ROLE_USER';
//    const ROLE_ADMIN = 'ROLE_ADMIN';
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=64)
     */
    private $name;

    /**
     * @Assert\NotBlank()
     * @Assert\Email()
     * @ORM\Column(type="string", length=128, unique=true)
     */
    private $email;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=128)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

//    /**
//     * A non-persisted field that's used to create the encoded password.
//     *
//     * @var string
//     */
//    private $plainPassword; // todo is this field really usefull? Just delete it!

    /**
     * User constructor.
     * The code inside __construct() is important: The $products property must be a collection object
     * that implements Doctrine's Collection interface. In this case, an ArrayCollection object is used.
     */
    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }


    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    /**
     * Used in twig templates
     * @return string
     */
    public function getImagePath(): ?string
    {
        return 'images/'.$this->imageFilename;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user AND add 'ROLE_USER' by default
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        // give everyone ROLE_USER!
        if (!in_array('ROLE_USER', $this->roles)) {
            $this->roles[] = 'ROLE_USER';
        }
        return $this->roles;
    }

    public function setRoles($roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
//        First getUsername()... is super-unimportant. Just return any unique user string you want -
// a username, an email, a uuid, a funny, but unique joke - whatever.
// This is only used to show you who is logged in when you're debugging
        return $this->name;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {

        // Security measure to prevent the plain-text password from being accidentally saved anywhere
        $this->plainPassword = null;
    }

//    /**
//     * @return string
//     */
//    public function getPlainPassword(): string
//    {
////        dump($this);die;
//        return $this->plainPassword;
//    }

//    /**
//     * @param string $plainPassword
//     */
//    public function setPlainPassword(string $plainPassword): void
//    {
//        $this->plainPassword = $plainPassword;
//        // forces the object to look "dirty" to Doctrine. Avoids
//        // Doctrine *not* saving this entity, if only plainPassword changes
//        $this->password = null;
//    }
}

full_tutorial/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('_username')
//            ->add('email')
            ->add('_password', PasswordType::class)
//            ->add('_password', RepeatedType::class, array(
//                'type' => PasswordType::class,
//                'first_options'  => array('label' => 'Password'),
//                'second_options' => array('label' => 'Repeat Password'),
//            ))
//            ->add('createdAt')
//            ->add('description')
//            ->add('imageFilename')
//            ->add('heartCount')
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
//        If you're building a login form that will be used with Symfony's native form_login system,
// override getBlockPrefix() and make it return an empty string.
// This will put the POST data in the proper place so the form_login system can find it.
//        return parent::getBlockPrefix();
        return '';
    }

//This is a rare time when I won't bother binding my form to a class.
//    public function configureOptions(OptionsResolver $resolver)
//    {
//        $resolver->setDefaults([
//            'data_class' => User::class,
//        ]);
//    }
}

full_tutorial/src/Controller/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pierre
 * Date: 04/05/2018
 * Time: 21:46
 */

namespace App\Controller;


//use Michelf\MarkdownInterface;
use App\Entity\User;
use App\Form\UserRegistrationType;
use App\Repository\UserRepository;
use App\Security\LoginFormAuthenticator;
use App\Service\MarkdownHelper;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Cache\Adapter\AdapterInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;

class UserController extends AbstractController
{
    private $logger;
    private $markdownHelper;

    function __construct(LoggerInterface $logger, MarkdownHelper $markdownHelper, $isDebug)
    {
        $this->logger = $logger;
        $this->markdownHelper = $markdownHelper;
    }

    /**
     * @Route("/", name="app_homepage")
     */
    public function homepage(UserRepository $repository){

//        $repository = $em->getRepository(User::class); // Prefered way => autowiring the repository
//        $users = $repository->findAll();
        // Nothing in the where close => we fetch all
//        $users = $repository->findBy([], ['createdAt' => 'DESC']);
        $users = $repository->findAllCreatedOrderedByNewest();
        return $this->render('user/homepage.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/user/{id}", name="show_user")
     */
    public function showUser(User $user){
        $comments = $user->getComments();

// No need to use these lines of code when we autowiring the entity. We just need to take care that the passed
// wildcard name is also an field name of the entity
//        $repository = $em->getRepository(User::class);
//        $user = $repository->findOneBy(['id' => $id]);
//        if (!$user) {
//            throw $this->createNotFoundException(sprintf('No user for id "%s"', $user));
//        }


        return $this->render('user/show.html.twig', [
            'user' => $user,
            'comments' => $comments,
        ]);
//        return new Response(sprintf('hello %s', $id));
    }

    /**
     * @Route("/news/{id}/heart", name="user_toggle_heart", methods={"post"})
     */
    public function toggleUserHeart(User $user, EntityManagerInterface $entityManager){

//        $this->logger->info('User heart: '.$user->getHeartCount());
        $user->incrementHeartCount();
        $entityManager->flush();

        return $this->json(['hearts' => $user->getHeartCount()]);
    }

    /**
     * @Route("/register", name="user_register")
     */
    public function registerAction(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardAuthenticatorHandler, LoginFormAuthenticator $loginFormAuthenticator)
    {
        $form = $this->createForm(UserRegistrationType::class);
        $form->handleRequest($request);
//        dump($form);die;
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $user = $form->getData();
//            dump($user);die;
            $user->setCreatedAt(new \DateTime())
                ->setPassword($passwordEncoder->encodePassword($user,$user->getPassword()));
            $user->getRoles();

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', 'Welcome '.$user->getEmail());
//            return $this->redirectToRoute('app_homepage');
            return $guardAuthenticatorHandler->authenticateUserAndHandleSuccess($user, $request, $loginFormAuthenticator, 'main');
        }

        return $this->render('user/register.html.twig', [
            'form' => $form->createView()
        ]);

    }

}

full_tutorial/templates/user/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <!-- Article List -->

            <div class="col-sm-12 col-md-8">

                <!-- H1 Article -->
                <a class="main-article-link" href="#">
                    <div class="main-article mb-5 pb-3">
                        <img src="{{ asset('images/meteor-shower.jpg') }}" alt="meteor shower">
                        <h1 class="text-center mt-2">Ursid Meteor Shower: <br>Healthier than a regular shower?</h1>
                    </div>
                </a>

                <!-- Supporting Articles -->

                {% for user in users %}

                    <div class="article-container my-1">
                        <a href="{{ path('show_user', { id: user.id}) }}">
                            <img class="article-img" src="{{ asset('images/asteroid.jpeg') }}">
                            <div class="article-title d-inline-block pl-3 align-middle">
                                <span>{{ user.name }}</span>
                                <br>
                                <span class="align-left article-details">
                                    <img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}"> {{ user.name }} </span>
                                <span class="pl-5 article-details float-right"> {{ user.createdAt|ago }}</span>
                            </div>
                        </a>
                    </div>
                {% endfor %}

                {#<div class="article-container my-1">#}
                    {#<a href="#">#}
                        {#<img class="article-img"  src="{{ asset('images/mercury.jpeg') }}">#}
                        {#<div class="article-title d-inline-block pl-3 align-middle">#}
                            {#<span>Life on Planet Mercury: <br> Tan, Relaxing and Fabulous</span>#}
                            {#<br>#}
                            {#<span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}"> Amy Oort </span>#}
                            {#<span class="pl-5 article-details float-right"> 6 days ago</span>#}
                        {#</div>#}
                    {#</a>#}
                {#</div>#}

                {#<div class="article-container my-1">#}
                    {#<a href="#">#}
                        {#<img class="article-img" src="{{ asset('images/lightspeed.png') }}">#}
                        {#<div class="article-title d-inline-block pl-3 align-middle">#}
                            {#<span>Light Speed Travel: <br> Fountain of Youth or Fallacy</span>#}
                            {#<br>#}
                            {#<span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}"> Amy Oort </span>#}
                            {#<span class="pl-5 article-details float-right"> 2 weeks ago</span>#}
                        {#</div>#}
                    {#</a>#}
                {#</div>#}

            </div>

            <!-- Right bar ad space -->


            <div class="col-sm-12 col-md-4 text-center">
                <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                    <img class="advertisement-img" src="{{ asset('images/space-ice.png') }}">
                    <p><span class="advertisement-text">New:</span> Space Ice Cream!</p>
                    <button class="btn btn-info">Buy Now!</button>
                </div>

                <div class="quote-space pb-2 pt-2 px-5">
                    <h3 class="text-center pb-3">Trending Quotes</h3>
                    <p><i class="fa fa-comment"></i> "Our two greatest problems are gravity and paperwork. We can lick gravity, but sometimes the paperwork is overwhelming." <br>— <a href="https://en.wikipedia.org/wiki/Wernher_von_Braun">Wernher von Braun, Rocket Engineer</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "Let's face it, space is a risky business. I always considered every launch a barely controlled explosion." <br>— <a href="https://en.wikipedia.org/wiki/Aaron_Cohen_(Deputy_NASA_administrator)">Aaron Cohen, NASA Administrator</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "If offered a seat on a rocket ship, don't ask what seat. Just get on."<br>— <a href="https://en.wikipedia.org/wiki/Christa_McAuliffe">Christa McAuliffe, Challenger Astronaut</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

full_tutorial/templates/user/register.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1>Register!</h1>
                {{ form_start(form) }}
                {{ form_row(form.name) }}
                {{ form_row(form.email) }}
                {{ form_row(form.description) }}
                {{ form_row(form.password.first, {
                    'label': 'Password'
                }) }}
                {{ form_row(form.password.second, {
                    'label': 'Repeat Password'
                }) }}

                <button type="submit" class="btn btn-primary" formnovalidate>Register</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

full_tutorial/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.name }}{% endblock %}

{% block body %}
{#{{ dump() }}#}
    <div class="container" xmlns="">
        <div class="row">
            <div class="col-sm-12">
                <div class="show-article-container p-3 mt-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <img class="show-article-img" src="{{ asset(user.imagePath) }}">
                            <div class="show-article-title-container d-inline-block pl-3 align-middle">
                                <span class="show-article-title ">{{ user.name }}?</span>
                                <br>
                                <span class="align-left article-details">
                                    <img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}"> {{ user.name }}
                                </span>
                                <span class="align-left article-details">
                                     {{ user.email }}
                                </span>
                                <span class="pl-2 article-details">{{ user.createdAt ? user.createdAt|ago : 'uncreated' }}</span>
                                <span class="pl-2 article-details">
                                    <span class="js-like-user-count">{{ user.heartCount }}</span>
                                    <a href="{{ path('user_toggle_heart', {id: user.id}) }}" class="fa fa-heart-o like-article js-like-user"></a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="article-text">
                                {{ user.description|cached_markdown }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p class="share-icons mb-5">
                                <span class="pr-1">Share:</span>
                                <i class="pr-1 fa fa-facebook-square"></i>
                                <i class="pr-1 fa fa-twitter-square"></i>
                                <i class="pr-1 fa fa-reddit-square"></i>
                                <i class="pr-1 fa fa-share-alt-square"></i>
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <h3><i class="pr-3 fa fa-comment"></i>{{ comments|length }} Comments</h3>
                            <hr>
                            <div class="row mb-5">
                                <div class="col-sm-12">
                                    <img class="comment-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}">
                                    <div class="comment-container d-inline-block pl-3 align-top">
                                        <span class="commenter-name">Amy Oort</span>
                                        <div class="form-group">
                                            <textarea class="form-control comment-form" id="articleText" rows="1"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-info">Comment</button>
                                    </div>
                                </div>
                            </div>
                            {% for comment in comments %}
                                <div class="row">
                                    <div class="col-sm-12">
                                        <img class="comment-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">
                                        <div class="comment-container d-inline-block pl-3 align-top">
                                            <span class="commenter-name">Mike Ferengi</span>
                                            <br>
                                            <span class="comment">{{ comment.comment }}</span>
                                            <p><a href="#">Reply</a></p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/user_show.js') }}"></script>
{% endblock %}